# Using https://github.com/tox-dev/azure-pipelines-template
# and learned from https://github.com/wasp/waspy/blob/master/azure-pipelines.yml

name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
resources:
  repositories:
  - repository: tox
    type: github
    endpoint: github
    name: tox-dev/azure-pipelines-template
    ref: refs/tags/0.2

trigger:
  batch: true
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

variables:
  PYTEST_ADDOPTS: "-v -v -ra --showlocals"
  PYTEST_XDIST_PROC_NR: 'auto'
  CI_RUN: 'yes'

jobs:
- template: run-tox-env.yml@tox
  parameters:
    jobs:
      fix_lint: null
      py36:
        image: [linux, windows, macOs]
      py37:
        image: [linux, windows, macOs]
      merge: null
      type: null
      package_readme: null
      dev: null
    before:
      - script: |
          python -m pip install --upgrade pip poetry
          poetry config settings.virtualenvs.create false
        displayName: 'setup'
      - script: poetry install && poetry develop
        displayName: 'install dependencies'
