[tool.poetry]
name = "cyberbrain"
version = "0.0.1"
description = "A Cyberbrain that helps you remember everything."
authors = ["laike9m <laike9m@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
bytecode = "^0.8.0"
uncompyle6 = "3.3.4"
crayons = "^0.2.0"
pytest-parallel = "^0.0.9"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
tox = "^3.13"
tox-run-command = "^0.4.0"
tox-pyenv = "^1.1"
pyhamcrest = "^1.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
